# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from dynamic_predictor/PredictedObstacle.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import dynamic_predictor.msg
import geometry_msgs.msg

class PredictedObstacle(genpy.Message):
  _md5sum = "6b1bfccd711ab582d4c8a979685459e6"
  _type = "dynamic_predictor/PredictedObstacle"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Obstacle identifier from tracker
int32 id

geometry_msgs/Point current_position
geometry_msgs/Vector3 current_velocity

# All modal trajectories for this obstacle
dynamic_predictor/PredictedTrajectory[] modes


================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: dynamic_predictor/PredictedTrajectory
# Probability weight of this mode
float64 probability

# Mean trajectory for this mode (length = horizon)
geometry_msgs/Point[] mean

# Variance per time step (same length as mean)
# Variance is ordered as var(x), var(y), var(z)
geometry_msgs/Vector3[] variance

"""
  __slots__ = ['id','current_position','current_velocity','modes']
  _slot_types = ['int32','geometry_msgs/Point','geometry_msgs/Vector3','dynamic_predictor/PredictedTrajectory[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,current_position,current_velocity,modes

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PredictedObstacle, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.current_position is None:
        self.current_position = geometry_msgs.msg.Point()
      if self.current_velocity is None:
        self.current_velocity = geometry_msgs.msg.Vector3()
      if self.modes is None:
        self.modes = []
    else:
      self.id = 0
      self.current_position = geometry_msgs.msg.Point()
      self.current_velocity = geometry_msgs.msg.Vector3()
      self.modes = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_i6d().pack(_x.id, _x.current_position.x, _x.current_position.y, _x.current_position.z, _x.current_velocity.x, _x.current_velocity.y, _x.current_velocity.z))
      length = len(self.modes)
      buff.write(_struct_I.pack(length))
      for val1 in self.modes:
        _x = val1.probability
        buff.write(_get_struct_d().pack(_x))
        length = len(val1.mean)
        buff.write(_struct_I.pack(length))
        for val2 in val1.mean:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        length = len(val1.variance)
        buff.write(_struct_I.pack(length))
        for val2 in val1.variance:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.current_position is None:
        self.current_position = geometry_msgs.msg.Point()
      if self.current_velocity is None:
        self.current_velocity = geometry_msgs.msg.Vector3()
      if self.modes is None:
        self.modes = None
      end = 0
      _x = self
      start = end
      end += 52
      (_x.id, _x.current_position.x, _x.current_position.y, _x.current_position.z, _x.current_velocity.x, _x.current_velocity.y, _x.current_velocity.z,) = _get_struct_i6d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.modes = []
      for i in range(0, length):
        val1 = dynamic_predictor.msg.PredictedTrajectory()
        start = end
        end += 8
        (val1.probability,) = _get_struct_d().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.mean = []
        for i in range(0, length):
          val2 = geometry_msgs.msg.Point()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          val1.mean.append(val2)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.variance = []
        for i in range(0, length):
          val2 = geometry_msgs.msg.Vector3()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          val1.variance.append(val2)
        self.modes.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_i6d().pack(_x.id, _x.current_position.x, _x.current_position.y, _x.current_position.z, _x.current_velocity.x, _x.current_velocity.y, _x.current_velocity.z))
      length = len(self.modes)
      buff.write(_struct_I.pack(length))
      for val1 in self.modes:
        _x = val1.probability
        buff.write(_get_struct_d().pack(_x))
        length = len(val1.mean)
        buff.write(_struct_I.pack(length))
        for val2 in val1.mean:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        length = len(val1.variance)
        buff.write(_struct_I.pack(length))
        for val2 in val1.variance:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.current_position is None:
        self.current_position = geometry_msgs.msg.Point()
      if self.current_velocity is None:
        self.current_velocity = geometry_msgs.msg.Vector3()
      if self.modes is None:
        self.modes = None
      end = 0
      _x = self
      start = end
      end += 52
      (_x.id, _x.current_position.x, _x.current_position.y, _x.current_position.z, _x.current_velocity.x, _x.current_velocity.y, _x.current_velocity.z,) = _get_struct_i6d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.modes = []
      for i in range(0, length):
        val1 = dynamic_predictor.msg.PredictedTrajectory()
        start = end
        end += 8
        (val1.probability,) = _get_struct_d().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.mean = []
        for i in range(0, length):
          val2 = geometry_msgs.msg.Point()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          val1.mean.append(val2)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.variance = []
        for i in range(0, length):
          val2 = geometry_msgs.msg.Vector3()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          val1.variance.append(val2)
        self.modes.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_d = None
def _get_struct_d():
    global _struct_d
    if _struct_d is None:
        _struct_d = struct.Struct("<d")
    return _struct_d
_struct_i6d = None
def _get_struct_i6d():
    global _struct_i6d
    if _struct_i6d is None:
        _struct_i6d = struct.Struct("<i6d")
    return _struct_i6d
