// Generated by gencpp from file dynamic_predictor/PredictedTrajectory.msg
// DO NOT EDIT!


#ifndef DYNAMIC_PREDICTOR_MESSAGE_PREDICTEDTRAJECTORY_H
#define DYNAMIC_PREDICTOR_MESSAGE_PREDICTEDTRAJECTORY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Vector3.h>

namespace dynamic_predictor
{
template <class ContainerAllocator>
struct PredictedTrajectory_
{
  typedef PredictedTrajectory_<ContainerAllocator> Type;

  PredictedTrajectory_()
    : probability(0.0)
    , mean()
    , variance()  {
    }
  PredictedTrajectory_(const ContainerAllocator& _alloc)
    : probability(0.0)
    , mean(_alloc)
    , variance(_alloc)  {
  (void)_alloc;
    }



   typedef double _probability_type;
  _probability_type probability;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _mean_type;
  _mean_type mean;

   typedef std::vector< ::geometry_msgs::Vector3_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Vector3_<ContainerAllocator> >> _variance_type;
  _variance_type variance;





  typedef boost::shared_ptr< ::dynamic_predictor::PredictedTrajectory_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamic_predictor::PredictedTrajectory_<ContainerAllocator> const> ConstPtr;

}; // struct PredictedTrajectory_

typedef ::dynamic_predictor::PredictedTrajectory_<std::allocator<void> > PredictedTrajectory;

typedef boost::shared_ptr< ::dynamic_predictor::PredictedTrajectory > PredictedTrajectoryPtr;
typedef boost::shared_ptr< ::dynamic_predictor::PredictedTrajectory const> PredictedTrajectoryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dynamic_predictor::PredictedTrajectory_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dynamic_predictor::PredictedTrajectory_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dynamic_predictor::PredictedTrajectory_<ContainerAllocator1> & lhs, const ::dynamic_predictor::PredictedTrajectory_<ContainerAllocator2> & rhs)
{
  return lhs.probability == rhs.probability &&
    lhs.mean == rhs.mean &&
    lhs.variance == rhs.variance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dynamic_predictor::PredictedTrajectory_<ContainerAllocator1> & lhs, const ::dynamic_predictor::PredictedTrajectory_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dynamic_predictor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dynamic_predictor::PredictedTrajectory_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamic_predictor::PredictedTrajectory_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamic_predictor::PredictedTrajectory_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamic_predictor::PredictedTrajectory_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamic_predictor::PredictedTrajectory_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamic_predictor::PredictedTrajectory_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dynamic_predictor::PredictedTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "48bdf4c0064d9378b7fbef39e2f807e0";
  }

  static const char* value(const ::dynamic_predictor::PredictedTrajectory_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x48bdf4c0064d9378ULL;
  static const uint64_t static_value2 = 0xb7fbef39e2f807e0ULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamic_predictor::PredictedTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dynamic_predictor/PredictedTrajectory";
  }

  static const char* value(const ::dynamic_predictor::PredictedTrajectory_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dynamic_predictor::PredictedTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Probability weight of this mode\n"
"float64 probability\n"
"\n"
"# Mean trajectory for this mode (length = horizon)\n"
"geometry_msgs/Point[] mean\n"
"\n"
"# Variance per time step (same length as mean)\n"
"# Variance is ordered as var(x), var(y), var(z)\n"
"geometry_msgs/Vector3[] variance\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::dynamic_predictor::PredictedTrajectory_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dynamic_predictor::PredictedTrajectory_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.probability);
      stream.next(m.mean);
      stream.next(m.variance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PredictedTrajectory_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamic_predictor::PredictedTrajectory_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dynamic_predictor::PredictedTrajectory_<ContainerAllocator>& v)
  {
    s << indent << "probability: ";
    Printer<double>::stream(s, indent + "  ", v.probability);
    s << indent << "mean[]" << std::endl;
    for (size_t i = 0; i < v.mean.size(); ++i)
    {
      s << indent << "  mean[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.mean[i]);
    }
    s << indent << "variance[]" << std::endl;
    for (size_t i = 0; i < v.variance.size(); ++i)
    {
      s << indent << "  variance[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "    ", v.variance[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYNAMIC_PREDICTOR_MESSAGE_PREDICTEDTRAJECTORY_H
