// Generated by gencpp from file dynamic_predictor/PredictedObstacle.msg
// DO NOT EDIT!


#ifndef DYNAMIC_PREDICTOR_MESSAGE_PREDICTEDOBSTACLE_H
#define DYNAMIC_PREDICTOR_MESSAGE_PREDICTEDOBSTACLE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Vector3.h>
#include <dynamic_predictor/PredictedTrajectory.h>

namespace dynamic_predictor
{
template <class ContainerAllocator>
struct PredictedObstacle_
{
  typedef PredictedObstacle_<ContainerAllocator> Type;

  PredictedObstacle_()
    : id(0)
    , current_position()
    , current_velocity()
    , modes()  {
    }
  PredictedObstacle_(const ContainerAllocator& _alloc)
    : id(0)
    , current_position(_alloc)
    , current_velocity(_alloc)
    , modes(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _current_position_type;
  _current_position_type current_position;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _current_velocity_type;
  _current_velocity_type current_velocity;

   typedef std::vector< ::dynamic_predictor::PredictedTrajectory_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::dynamic_predictor::PredictedTrajectory_<ContainerAllocator> >> _modes_type;
  _modes_type modes;





  typedef boost::shared_ptr< ::dynamic_predictor::PredictedObstacle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamic_predictor::PredictedObstacle_<ContainerAllocator> const> ConstPtr;

}; // struct PredictedObstacle_

typedef ::dynamic_predictor::PredictedObstacle_<std::allocator<void> > PredictedObstacle;

typedef boost::shared_ptr< ::dynamic_predictor::PredictedObstacle > PredictedObstaclePtr;
typedef boost::shared_ptr< ::dynamic_predictor::PredictedObstacle const> PredictedObstacleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dynamic_predictor::PredictedObstacle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dynamic_predictor::PredictedObstacle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dynamic_predictor::PredictedObstacle_<ContainerAllocator1> & lhs, const ::dynamic_predictor::PredictedObstacle_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.current_position == rhs.current_position &&
    lhs.current_velocity == rhs.current_velocity &&
    lhs.modes == rhs.modes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dynamic_predictor::PredictedObstacle_<ContainerAllocator1> & lhs, const ::dynamic_predictor::PredictedObstacle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dynamic_predictor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dynamic_predictor::PredictedObstacle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamic_predictor::PredictedObstacle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamic_predictor::PredictedObstacle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamic_predictor::PredictedObstacle_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamic_predictor::PredictedObstacle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamic_predictor::PredictedObstacle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dynamic_predictor::PredictedObstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6b1bfccd711ab582d4c8a979685459e6";
  }

  static const char* value(const ::dynamic_predictor::PredictedObstacle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6b1bfccd711ab582ULL;
  static const uint64_t static_value2 = 0xd4c8a979685459e6ULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamic_predictor::PredictedObstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dynamic_predictor/PredictedObstacle";
  }

  static const char* value(const ::dynamic_predictor::PredictedObstacle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dynamic_predictor::PredictedObstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Obstacle identifier from tracker\n"
"int32 id\n"
"\n"
"geometry_msgs/Point current_position\n"
"geometry_msgs/Vector3 current_velocity\n"
"\n"
"# All modal trajectories for this obstacle\n"
"dynamic_predictor/PredictedTrajectory[] modes\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: dynamic_predictor/PredictedTrajectory\n"
"# Probability weight of this mode\n"
"float64 probability\n"
"\n"
"# Mean trajectory for this mode (length = horizon)\n"
"geometry_msgs/Point[] mean\n"
"\n"
"# Variance per time step (same length as mean)\n"
"# Variance is ordered as var(x), var(y), var(z)\n"
"geometry_msgs/Vector3[] variance\n"
"\n"
;
  }

  static const char* value(const ::dynamic_predictor::PredictedObstacle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dynamic_predictor::PredictedObstacle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.current_position);
      stream.next(m.current_velocity);
      stream.next(m.modes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PredictedObstacle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamic_predictor::PredictedObstacle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dynamic_predictor::PredictedObstacle_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "current_position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.current_position);
    s << indent << "current_velocity: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.current_velocity);
    s << indent << "modes[]" << std::endl;
    for (size_t i = 0; i < v.modes.size(); ++i)
    {
      s << indent << "  modes[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::dynamic_predictor::PredictedTrajectory_<ContainerAllocator> >::stream(s, indent + "    ", v.modes[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYNAMIC_PREDICTOR_MESSAGE_PREDICTEDOBSTACLE_H
