// Generated by gencpp from file dynamic_predictor/PredictedObstacles.msg
// DO NOT EDIT!


#ifndef DYNAMIC_PREDICTOR_MESSAGE_PREDICTEDOBSTACLES_H
#define DYNAMIC_PREDICTOR_MESSAGE_PREDICTEDOBSTACLES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <dynamic_predictor/PredictedObstacle.h>

namespace dynamic_predictor
{
template <class ContainerAllocator>
struct PredictedObstacles_
{
  typedef PredictedObstacles_<ContainerAllocator> Type;

  PredictedObstacles_()
    : header()
    , obstacles()  {
    }
  PredictedObstacles_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , obstacles(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::dynamic_predictor::PredictedObstacle_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::dynamic_predictor::PredictedObstacle_<ContainerAllocator> >> _obstacles_type;
  _obstacles_type obstacles;





  typedef boost::shared_ptr< ::dynamic_predictor::PredictedObstacles_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamic_predictor::PredictedObstacles_<ContainerAllocator> const> ConstPtr;

}; // struct PredictedObstacles_

typedef ::dynamic_predictor::PredictedObstacles_<std::allocator<void> > PredictedObstacles;

typedef boost::shared_ptr< ::dynamic_predictor::PredictedObstacles > PredictedObstaclesPtr;
typedef boost::shared_ptr< ::dynamic_predictor::PredictedObstacles const> PredictedObstaclesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dynamic_predictor::PredictedObstacles_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dynamic_predictor::PredictedObstacles_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dynamic_predictor::PredictedObstacles_<ContainerAllocator1> & lhs, const ::dynamic_predictor::PredictedObstacles_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.obstacles == rhs.obstacles;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dynamic_predictor::PredictedObstacles_<ContainerAllocator1> & lhs, const ::dynamic_predictor::PredictedObstacles_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dynamic_predictor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dynamic_predictor::PredictedObstacles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamic_predictor::PredictedObstacles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamic_predictor::PredictedObstacles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamic_predictor::PredictedObstacles_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamic_predictor::PredictedObstacles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamic_predictor::PredictedObstacles_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dynamic_predictor::PredictedObstacles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "de883972cf9be65d742bb9007ac50081";
  }

  static const char* value(const ::dynamic_predictor::PredictedObstacles_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xde883972cf9be65dULL;
  static const uint64_t static_value2 = 0x742bb9007ac50081ULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamic_predictor::PredictedObstacles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dynamic_predictor/PredictedObstacles";
  }

  static const char* value(const ::dynamic_predictor::PredictedObstacles_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dynamic_predictor::PredictedObstacles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"dynamic_predictor/PredictedObstacle[] obstacles\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: dynamic_predictor/PredictedObstacle\n"
"# Obstacle identifier from tracker\n"
"int32 id\n"
"\n"
"geometry_msgs/Point current_position\n"
"geometry_msgs/Vector3 current_velocity\n"
"\n"
"# All modal trajectories for this obstacle\n"
"dynamic_predictor/PredictedTrajectory[] modes\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: dynamic_predictor/PredictedTrajectory\n"
"# Probability weight of this mode\n"
"float64 probability\n"
"\n"
"# Mean trajectory for this mode (length = horizon)\n"
"geometry_msgs/Point[] mean\n"
"\n"
"# Variance per time step (same length as mean)\n"
"# Variance is ordered as var(x), var(y), var(z)\n"
"geometry_msgs/Vector3[] variance\n"
"\n"
;
  }

  static const char* value(const ::dynamic_predictor::PredictedObstacles_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dynamic_predictor::PredictedObstacles_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.obstacles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PredictedObstacles_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamic_predictor::PredictedObstacles_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dynamic_predictor::PredictedObstacles_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "obstacles[]" << std::endl;
    for (size_t i = 0; i < v.obstacles.size(); ++i)
    {
      s << indent << "  obstacles[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::dynamic_predictor::PredictedObstacle_<ContainerAllocator> >::stream(s, indent + "    ", v.obstacles[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYNAMIC_PREDICTOR_MESSAGE_PREDICTEDOBSTACLES_H
