#!/usr/bin/env python3
"""
Flight Data Analysis Script
Analyzes CSV files generated by the data recorder node
"""

import pandas as pd
import numpy as np
import sys
import os
import glob

def analyze_flight_data(csv_file):
    """
    Analyze flight data from CSV file and compute metrics
    
    Metrics:
    1. CR (Collision Rate): collision count / total frames × 100%
    2. Dmin (Minimum Distance): minimum distance to obstacles during flight
    3. L (Path Length): total path length traveled
    4. IR (Infeasible Rate): infeasible count / total frames × 100%
    """
    
    print("=" * 60)
    print(f"Analyzing: {csv_file}")
    print("=" * 60)
    
    # Read CSV
    try:
        df = pd.read_csv(csv_file)
    except Exception as e:
        print(f"Error reading CSV file: {e}")
        return None
    
    # Check if CSV is valid
    if len(df) == 0:
        print("Warning: CSV file is empty!")
        return None
    
    # Calculate metrics
    total_frames = len(df)
    collision_count = df['collision_flag'].sum()
    infeasible_count = df['infeasible_flag'].sum()
    
    # Collision Rate (CR)
    collision_rate = (collision_count / total_frames) * 100 if total_frames > 0 else 0
    
    # Minimum Distance (Dmin)
    min_distance = df['dist_min'].min()
    mean_distance = df['dist_min'].mean()
    std_distance = df['dist_min'].std()
    
    # Path Length (L)
    path_length = df['path_length'].iloc[-1] if len(df) > 0 else 0
    
    # Infeasible Rate (IR)
    infeasible_rate = (infeasible_count / total_frames) * 100 if total_frames > 0 else 0
    
    # Flight time
    flight_time = df['time'].iloc[-1] if len(df) > 0 else 0
    
    # Print results
    print(f"\n飞行数据统计:")
    print(f"  总帧数: {total_frames}")
    print(f"  飞行时间: {flight_time:.2f} 秒")
    print(f"\n关键指标:")
    print(f"  1. 碰撞率 (CR): {collision_rate:.2f}% ({collision_count}/{total_frames} 帧)")
    print(f"  2. 最小距离 (Dmin): {min_distance:.3f} m")
    print(f"     平均距离: {mean_distance:.3f} ± {std_distance:.3f} m")
    print(f"  3. 路径长度 (L): {path_length:.3f} m")
    print(f"  4. 无解率 (IR): {infeasible_rate:.2f}% ({infeasible_count}/{total_frames} 帧)")
    
    # Additional analysis
    print(f"\n额外信息:")
    print(f"  起点: ({df['uav_x'].iloc[0]:.2f}, {df['uav_y'].iloc[0]:.2f}, {df['uav_z'].iloc[0]:.2f})")
    print(f"  终点: ({df['uav_x'].iloc[-1]:.2f}, {df['uav_y'].iloc[-1]:.2f}, {df['uav_z'].iloc[-1]:.2f})")
    print(f"  平均速度: {path_length / flight_time:.3f} m/s" if flight_time > 0 else "N/A")
    
    # Warning messages
    if collision_count > 0:
        print(f"\n⚠️  警告: 检测到 {collision_count} 次碰撞!")
        collision_times = df[df['collision_flag'] == 1]['time'].values
        print(f"    碰撞时刻: {collision_times[:5]}..." if len(collision_times) > 5 else f"    碰撞时刻: {collision_times}")
    
    if infeasible_count > 0:
        print(f"\n⚠️  警告: MPC求解失败 {infeasible_count} 次!")
    
    print("=" * 60)
    
    # Return metrics as dict
    metrics = {
        'file': csv_file,
        'total_frames': total_frames,
        'flight_time': flight_time,
        'collision_rate': collision_rate,
        'collision_count': collision_count,
        'min_distance': min_distance,
        'mean_distance': mean_distance,
        'std_distance': std_distance,
        'path_length': path_length,
        'infeasible_rate': infeasible_rate,
        'infeasible_count': infeasible_count,
        'avg_velocity': path_length / flight_time if flight_time > 0 else 0
    }
    
    return metrics

def analyze_multiple_runs(csv_pattern):
    """
    Analyze multiple flight data files and compute statistics
    """
    csv_files = glob.glob(csv_pattern)
    
    if len(csv_files) == 0:
        print(f"No files found matching pattern: {csv_pattern}")
        return
    
    print(f"\nFound {len(csv_files)} CSV files to analyze\n")
    
    all_metrics = []
    for csv_file in csv_files:
        metrics = analyze_flight_data(csv_file)
        if metrics:
            all_metrics.append(metrics)
        print()
    
    if len(all_metrics) == 0:
        print("No valid data to analyze")
        return
    
    # Compute aggregate statistics
    print("\n" + "=" * 60)
    print("聚合统计 (所有实验)")
    print("=" * 60)
    
    df_metrics = pd.DataFrame(all_metrics)
    
    print(f"\n总实验次数: {len(all_metrics)}")
    print(f"\n关键指标均值 ± 标准差:")
    print(f"  碰撞率 (CR): {df_metrics['collision_rate'].mean():.2f} ± {df_metrics['collision_rate'].std():.2f}%")
    print(f"  最小距离 (Dmin): {df_metrics['min_distance'].mean():.3f} ± {df_metrics['min_distance'].std():.3f} m")
    print(f"  路径长度 (L): {df_metrics['path_length'].mean():.3f} ± {df_metrics['path_length'].std():.3f} m")
    print(f"  无解率 (IR): {df_metrics['infeasible_rate'].mean():.2f} ± {df_metrics['infeasible_rate'].std():.2f}%")
    print(f"  平均速度: {df_metrics['avg_velocity'].mean():.3f} ± {df_metrics['avg_velocity'].std():.3f} m/s")
    
    # Success rate (no collision)
    success_count = len(df_metrics[df_metrics['collision_count'] == 0])
    success_rate = (success_count / len(all_metrics)) * 100
    print(f"\n成功率 (无碰撞): {success_rate:.2f}% ({success_count}/{len(all_metrics)})")
    
    print("=" * 60)

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage:")
        print("  python3 analyze_flight_data.py <csv_file>")
        print("  python3 analyze_flight_data.py 'flight_data_*.csv'  # analyze multiple files")
        print("\nExample:")
        print("  python3 analyze_flight_data.py flight_data_20260107_123456.csv")
        print("  python3 analyze_flight_data.py 'flight_data_*.csv'")
        sys.exit(1)
    
    csv_input = sys.argv[1]
    
    # Check if it's a pattern or single file
    if '*' in csv_input:
        analyze_multiple_runs(csv_input)
    else:
        if os.path.exists(csv_input):
            analyze_flight_data(csv_input)
        else:
            print(f"Error: File not found: {csv_input}")
            sys.exit(1)



