(cl:defpackage dynamic_predictor-msg
  (:use )
  (:export
   "<PREDICTEDOBSTACLE>"
   "PREDICTEDOBSTACLE"
   "<PREDICTEDOBSTACLES>"
   "PREDICTEDOBSTACLES"
   "<PREDICTEDTRAJECTORY>"
   "PREDICTEDTRAJECTORY"
  ))

